version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    # container_name: folowup_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - storage_data:/var/www/storage
    depends_on:
      db:
        condition: service_healthy
    networks:
      - folowup

        #  nginx:
        # image: nginx:alpine
        #container_name: folowup_nginx
        # restart: unless-stopped
        # ports:
        #  - "80:80"
        #    volumes:
        #      - .:/var/www
        #      - ./docker/nginx:/etc/nginx/conf.d
        #    depends_on:
        #      - app
        #    networks:
        #      - folowup

  db:
    image: mysql:8.0
    # container_name: folowup_db
    restart: unless-stopped
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MYSQL_DATABASE: folowup
      MYSQL_USER: folowup_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - folowup

networks:
  folowup:

volumes:
  dbdata:

